pre-release-commit-message = "chore/release: ğŸ‰ {{version}} ğŸ‰"
# TODO creates tmp files which cargo release does not appreciate
#pre-release-hook = ["cargo", "test"]
tag-prefix = "v"
no-dev-version = true